

all: bp community forums helpcenter kb veeamhub
clean:
	rm -I -v .*.cache
bp:
	./bp.py
community:
	./community.py
forums:
	./forums.py
helpcenter:
	./helpcenter.py
kb:
	./kb.py
veeamhub:
	./veeamhub.py
